title = "Matt Majestic Portfolio"
baseURL = "https://upbeat-swartz-7f78a9.netlify.app/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "EST"
email = "mattmajestic@protonmail.com"
favicon = "/favicon.ico"
firstName = "Matt"
lastName = "Majestic"
profileImage = "img/mm_gh_small.png"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/matthew-majestic/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/mattmajestic/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
